version: 1.0.{build}
image: Visual Studio 2017

environment:
  DOCKER_USER:
    secure: WiNRm6G//OtBaMDCSnmXig==
  DOCKER_PASS:
    secure: 0ymXpkVnG1Tu6B/eO/O/Hg==

install:
  - ps: Write-Host Server version $(gp 'HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion').BuildLabEx
  - docker version

build_script:
  - ps: .\build.ps1

test: off